### ISSUE TITLE
Dashboard not working with non-standard base-path

### ISSUE THREAD

**Issue by fehmer** [MartinDevillers/spring-boot-admin-hystrix-dashboard#1]
Hi @MartinDevillers , thanks a lot for publishing the dashboard.

When using a non-standard actuator-endpoint opening the hystrix dashboard results in a 404 error page.

Actuator config:
```yaml
management:
  endpoints:
    web:
      base-path: /manage
```

Manage endpoint shows up correctly in SBA, link in /manage points to the right hystrix.stream as well.

Versions:
- spring-boot-admin-hystrix-dashboard 1.0.1
- Spring 2.1.6.Release
- Spring Cloud Greenwich.SR2
